substitutions:
  device_name: "Athom 3 Gang Switch"
  device_id: "athom-3gang-switch"
  light1_restore_mode: RESTORE_DEFAULT_OFF
  light2_restore_mode: RESTORE_DEFAULT_OFF
  light3_restore_mode: RESTORE_DEFAULT_OFF
  board: esp8285
  ip_address: 192.168.0.169
  ota_pwd: !secret ota_password
  api_key: "Xyerfqc2TgbzJ5BEc2PkMvOyLFmc9A+cQA1bidbcvYU="
  ap_wifi_pwd: !secret ap_password

web_server:
  port: 80

packages:
  device_base: !include ./packages/device_base_esp8266.yaml

binary_sensor:
  - platform: status
    name: "Status"

  # Touch Buttons
  - platform: gpio
    pin:
      inverted: true
      number: GPIO12
      mode:
        input: true
        pullup: true
    name: "Button1"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: gpio
    pin:
      inverted: true
      number: GPIO3
      mode:
        input: true
        pullup: true
    name: "Button2"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light2

  - platform: gpio
    pin:
      inverted: true
      number: GPIO5
      mode:
        input: true
        pullup: true
    name: "Button3"
    disabled_by_default: true
    on_click:
      max_length: 0.5s
      then:
        - light.toggle: light3

button:
  - platform: factory_reset
    name: "Reset"
    id: Reset

  - platform: safe_mode
    name: "Safe Mode"
    internal: false

output:
  # Relays
  - platform: gpio
    pin: GPIO13
    id: relay1
  - platform: gpio
    pin: GPIO4
    id: relay2
  - platform: gpio
    pin: GPIO15
    id: relay3

  # Button LEDs (1.0 = Blue / 0.0 = Red)
  - platform: esp8266_pwm
    pin: GPIO16
    inverted: true
    id: button_led1
  - platform: esp8266_pwm
    pin: GPIO14
    inverted: true
    id: button_led2
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: true
    id: button_led3

light:
  - platform: status_led
    name: "Status LED"
    disabled_by_default: true
    pin:
      number: GPIO0
      inverted: true

  # Relays
  - platform: binary
    name: "Light1"
    id: light1
    output: relay1
    restore_mode: ${light1_restore_mode}
    on_turn_on:
      - light.turn_on: led1
    on_turn_off:
      - light.turn_off: led1

  - platform: binary
    name: "Light2"
    id: light2
    output: relay2
    restore_mode: ${light2_restore_mode}
    on_turn_on:
      - light.turn_on: led2
    on_turn_off:
      - light.turn_off: led2

  - platform: binary
    name: "Light3"
    id: light3
    output: relay3
    restore_mode: ${light3_restore_mode}
    on_turn_on:
      - light.turn_on: led3
    on_turn_off:
      - light.turn_off: led3

  # Button LEDs
  - platform: monochromatic
    name: "LED1"
    disabled_by_default: true
    id: led1
    output: button_led1
    default_transition_length: 500ms
  - platform: monochromatic
    name: "LED2"
    disabled_by_default: true
    id: led2
    output: button_led2
    default_transition_length: 500ms
  - platform: monochromatic
    name: "LED3"
    disabled_by_default: true
    id: led3
    output: button_led3
    default_transition_length: 500ms

